config/routes.rb
Ratr::Application.routes.draw do
  root "movies#public"
  get "movies/:id/upvote", to: "movies#upvote", as: 'upvote_movie'
  resources :movies

end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :upvote]

  def public
    upcoming_api_movies = Tmdb::Movie.upcoming
    popular_api_movies = Tmdb::Movie.popular
    now_playing_api_movies = Tmdb::Movie.now_playing
    top_rated_api_movies = Tmdb::Movie.top_rated

    upcoming_api_movies.each do |api_movie|
      create_from_api_movie(api_movie, 'upcoming')
    end

    popular_api_movies.each do |api_movie|
      create_from_api_movie(api_movie, 'popular')
    end

    now_playing_api_movies.each do |api_movie|
      create_from_api_movie(api_movie, 'now_playing')
    end

    top_rated_api_movies.each do |api_movie|
      create_from_api_movie(api_movie, 'top_rated')
    end

    @top_rated = Movie.where(category:'top_rated')
    @now_playing = Movie.where(category:'now_playing')
    @popular = Movie.where(category:'popular')
    @upcoming = Movie.where(category:'upcoming')

  end

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  def upvote
    @movie.upvotes += 1
    respond_to do |format|
      if @movie.save
        format.js
      else
        logger.error "COULD NOT SAVE MOVIE UPVOTE"
      end
    end
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @movie }
      else
        format.html { render action: 'new' }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :upvotes, :description)
    end

    def create_from_api_movie api_movie, category=nil
      movie = Movie.where(id:api_movie["id"]).first_or_initialize()
      movie.title = api_movie["title"]
      movie.release_date = api_movie["release_date"]
      movie.category = category
      movie.save
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ratr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :upvotes %><br>
    <%= f.number_field :upvotes %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Upvotes</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.upvotes %></td>
        <td><%= movie.description %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/public.html.erb
<h1>Upcoming:</h1>
<ul>
<% @upcoming.each do |movie| %>
  <li>
    <%= link_to 'upvote', upvote_movie_path(movie), remote:true %>
    [<span id="upvote-count-<%= movie.id %>"><%= movie.upvotes %></span>]
    <%= movie.title %>  - <%= movie.release_date %>
  </li>
<% end %>
</ul>

<h1>Now Playing:</h1>
<ul>
<% @now_playing.each do |movie| %>
  <li>
    <%= link_to 'upvote', upvote_movie_path(movie), remote:true %>
    [<span id="upvote-count-<%= movie.id %>"><%= movie.upvotes %></span>]
    <%= movie.title %>  - <%= movie.release_date %>
  </li>
<% end %>
</ul>

<h1>Top Rated:</h1>
<ul>
<% @top_rated.each do |movie| %>
  <li>
    <%= link_to 'upvote', upvote_movie_path(movie), remote:true %>
    [<span id="upvote-count-<%= movie.id %>"><%= movie.upvotes %></span>]
    <%= movie.title %>  - <%= movie.release_date %>
  </li>
<% end %>
</ul>

<h1>Popular:</h1>
<ul>
<% @popular.each do |movie| %>
  <li>
    <%= link_to 'upvote', upvote_movie_path(movie), remote:true %>
    [<span id="upvote-count-<%= movie.id %>"><%= movie.upvotes %></span>]
    <%= movie.title %>  - <%= movie.release_date %>
  </li>
<% end %>
</ul>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Upvotes:</strong>
  <%= @movie.upvotes %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/movies/upvote.js.erb
(function() {
  var $new_count = <%= @movie.upvotes %>;
  $('#upvote-count-<%= @movie.id %>').text($new_count);
})()